export const products = [
  {
    id: 1,
    name: 'Mushroom - White Button',
    price: 10,
    categoryId: 1,
    quantitySold: 0,
  },
  { id: 2, name: 'Beer - Guiness', price: 20, categoryId: 1, quantitySold: 0 },
  {
    id: 3,
    name: 'Bread - Pita, Mini',
    price: 30,
    categoryId: 1,
    quantitySold: 0,
  },
  {
    id: 4,
    name: 'Munchies Honey Sweet Trail Mix',
    price: 40,
    categoryId: 1,
    quantitySold: 0,
  },
  { id: 5, name: 'Cakes Assorted', price: 50, categoryId: 1, quantitySold: 0 },
  {
    id: 6,
    name: 'Vinegar - Red Wine',
    price: 60,
    categoryId: 1,
    quantitySold: 0,
  },
  {
    id: 7,
    name: 'Syrup - Monin, Irish Cream',
    price: 70,
    categoryId: 1,
    quantitySold: 0,
  },
  {
    id: 8,
    name: 'French Pastry - Mini Chocolate',
    price: 80,
    categoryId: 2,
    quantitySold: 0,
  },
  {
    id: 9,
    name: 'Ham Black Forest',
    price: 90,
    categoryId: 2,
    quantitySold: 0,
  },
  {
    id: 10,
    name: 'Muffin Hinge Container 6',
    price: 100,
    categoryId: 2,
    quantitySold: 0,
  },
  { id: 11, name: 'Rambutan', price: 110, categoryId: 2, quantitySold: 0 },
  { id: 12, name: 'Beans - Wax', price: 120, categoryId: 2, quantitySold: 0 },
  {
    id: 13,
    name: 'Wine - Sauvignon Blanc Oyster',
    price: 130,
    categoryId: 2,
    quantitySold: 0,
  },
  {
    id: 14,
    name: 'Wine - Taylors Reserve',
    price: 140,
    categoryId: 2,
    quantitySold: 0,
  },
  {
    id: 15,
    name: 'Wine - Ej Gallo Sierra Valley',
    price: 150,
    categoryId: 2,
    quantitySold: 0,
  },
  { id: 16, name: 'Flour - Bread', price: 160, categoryId: 2, quantitySold: 0 },
  { id: 17, name: 'Wasabi Paste', price: 170, categoryId: 3, quantitySold: 0 },
  {
    id: 18,
    name: 'Beer - Pilsner Urquell',
    price: 180,
    categoryId: 3,
    quantitySold: 0,
  },
  {
    id: 19,
    name: 'Pasta - Lasagna Noodle, Frozen',
    price: 190,
    categoryId: 3,
    quantitySold: 0,
  },
  {
    id: 20,
    name: 'Chips - Doritos',
    price: 200,
    categoryId: 3,
    quantitySold: 0,
  },
  { id: 21, name: 'Basil - Fresh', price: 210, categoryId: 3, quantitySold: 0 },
  {
    id: 22,
    name: 'Soup - Knorr, Chicken Noodle',
    price: 220,
    categoryId: 3,
    quantitySold: 0,
  },
  { id: 23, name: 'Duck - Legs', price: 230, categoryId: 3, quantitySold: 0 },
  {
    id: 24,
    name: 'Lemonade - Mandarin, 591 Ml',
    price: 240,
    categoryId: 3,
    quantitySold: 0,
  },
  {
    id: 25,
    name: 'Bar - Sweet And Salty Chocolate',
    price: 250,
    categoryId: 3,
    quantitySold: 0,
  },
  { id: 26, name: 'Filo Dough', price: 260, categoryId: 3, quantitySold: 0 },
  {
    id: 27,
    name: 'Turkey - Breast, Double',
    price: 270,
    categoryId: 3,
    quantitySold: 0,
  },
  { id: 28, name: 'Cheese - Goat', price: 280, categoryId: 3, quantitySold: 0 },
  {
    id: 29,
    name: 'Mushroom - Shitake, Dry',
    price: 290,
    categoryId: 3,
    quantitySold: 0,
  },
  {
    id: 30,
    name: 'Lamb Shoulder Boneless Nz',
    price: 300,
    categoryId: 3,
    quantitySold: 0,
  },
  {
    id: 31,
    name: 'Ginsing - Fresh',
    price: 300,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 32,
    name: 'Brandy Cherry - Mcguinness',
    price: 320,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 33,
    name: 'Arizona - Green Tea',
    price: 330,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 34,
    name: 'Dc - Frozen Momji',
    price: 340,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 35,
    name: 'Chicken - Ground',
    price: 350,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 36,
    name: 'Mushroom Morel Fresh',
    price: 360,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 37,
    name: 'Soup - Knorr, Veg / Beef',
    price: 370,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 38,
    name: 'Turkey Tenderloin Frozen',
    price: 380,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 39,
    name: 'Soup - French Onion',
    price: 390,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 40,
    name: 'Ecolab - Lime - A - Way 4/4 L',
    price: 400,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 41,
    name: 'Tilapia - Fillets',
    price: 410,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 42,
    name: 'Steampan - Lid For Half Size',
    price: 420,
    categoryId: 4,
    quantitySold: 0,
  },
  {
    id: 43,
    name: 'Bread Base - Italian',
    price: 430,
    categoryId: 5,
    quantitySold: 0,
  },
  {
    id: 44,
    name: 'Turnip - White',
    price: 440,
    categoryId: 5,
    quantitySold: 0,
  },
  { id: 45, name: 'Dry Ice', price: 450, categoryId: 5, quantitySold: 0 },
  {
    id: 46,
    name: 'Water - Evian 355 Ml',
    price: 460,
    categoryId: 5,
    quantitySold: 0,
  },
  { id: 47, name: 'Tumeric', price: 470, categoryId: 5, quantitySold: 0 },
  {
    id: 48,
    name: 'Wine - Valpolicella Masi',
    price: 480,
    categoryId: 5,
    quantitySold: 0,
  },
  {
    id: 49,
    name: 'Wine - Rosso Toscano Igt',
    price: 490,
    categoryId: 5,
    quantitySold: 0,
  },
  {
    id: 50,
    name: 'Cut Wakame - Hanawakaba',
    price: 500,
    categoryId: 5,
    quantitySold: 0,
  },
];
